### ISSUE TITLE
无法将org2的节点加入通道

### ISSUE THREAD

**Issue by Vancir** [Vancir/fugitivec#4]
不能将org2创建的两个节点`peer0_org2`和`peer1_org2`加入通道`mychannel`中, 如下为报错信息

``` bash
2018-12-14 21:40:28 WARN  Config:127 - Failed to load any configuration from: config.properties. Using toolkit defaults
2018-12-14 21:40:29 INFO  Channel:770 - Channel{id: 3, name: mychannel} joining Peer{ id: 5, name: peer0.org1.vancir.com, channelName: null, url: grpc://localhost:7051}.
2018-12-14 21:40:30 INFO  Channel:802 - Peer Peer{ id: 5, name: peer0.org1.vancir.com, channelName: mychannel, url: grpc://localhost:7051} joined into channel Channel{id: 3, name: mychannel}
2018-12-14 21:40:30 INFO  Channel:770 - Channel{id: 3, name: mychannel} joining Peer{ id: 6, name: peer1.org1.vancir.com, channelName: null, url: grpc://localhost:7056}.
2018-12-14 21:40:30 INFO  Channel:802 - Peer Peer{ id: 6, name: peer1.org1.vancir.com, channelName: mychannel, url: grpc://localhost:7056} joined into channel Channel{id: 3, name: mychannel}
2018-12-14 21:40:30 INFO  Channel:1147 - Channel Channel{id: 3, name: mychannel} eventThread started shutdown: false  thread: null
2018-12-14 21:40:30 INFO  Channel:770 - Channel{id: 3, name: mychannel} joining Peer{ id: 7, name: peer0.org2.vancir.com, channelName: null, url: grpc://localhost:8051}.
2018-12-14 21:40:30 WARN  PeerEventServiceClient:230 - PeerEventServiceClient{id: 16, channel: mychannel, peerName: peer0.org2.vancir.com, url: grpc://localhost:8051} PeerEventServiceClient{id: 16, channel: mychannel, peerName:peer0.org2.vancir.com, url: grpc://localhost:8051} attempts 0 Status returned failure code 404 (NOT_FOUND) during peer service event registration
2018-12-14 21:40:30 ERROR Channel:4138 - Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: cad200fc59cc5e96cf11f9d2b692d830a4ac7ce990a6533502b9e599618708bf to Peer{ id: 7, name: peer0.org2.vancir.com, channelName: mychannel, url: grpc://localhost:8051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [] creator org [Org2MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [] creator org [Org2MSP]
        at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4138)
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:796)
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:736)
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:693)
        at com.vancir.network.CreateChannel.main(CreateChannel.java:74)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [] creator org [Org2MSP]
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-12-14 21:40:30 ERROR Channel:810 - Channel{id: 3, name: mychannel} removing peer Peer{ id: 7, name: peer0.org2.vancir.com, channelName: mychannel, url: grpc://localhost:8051} due to exception Join peer to channel mychannelfailed.  Status FAILURE, details: Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: cad200fc59cc5e96cf11f9d2b692d830a4ac7ce990a6533502b9e599618708bf to Peer{ id: 7, name: peer0.org2.vancir.com, channelName: mychannel, url: grpc://localhost:8051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [] creator org [Org2MSP], cause=null}
2018-12-14 21:40:30 ERROR Channel:812 - org.hyperledger.fabric.sdk.exception.ProposalException: Join peer to channel mychannel failed.  Status FAILURE, details: Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: cad200fc59cc5e96cf11f9d2b692d830a4ac7ce990a6533502b9e599618708bf to Peer{ id: 7, name: peer0.org2.vancir.com, channelName: mychannel, url: grpc://localhost:8051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [] creator org [Org2MSP], cause=null}
org.hyperledger.fabric.sdk.exception.ProposalException: Join peer to channel mychannel failed.  Status FAILURE, details: Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: cad200fc59cc5e96cf11f9d2b692d830a4ac7ce990a6533502b9e599618708bf to Peer{ id: 7, name: peer0.org2.vancir.com, channelName: mychannel, url: grpc://localhost:8051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [] creator org [Org2MSP], cause=null}
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:805)
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:736)
        at org.hyperledger.fabric.sdk.Channel.joinPeer(Channel.java:693)
        at com.vancir.network.CreateChannel.main(CreateChannel.java:74)
2018-12-14 21:40:30 ERROR Channel:4138 - Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: 3eb2848343a9f86e6d1e3de97748885759b2ecc954607c6b6eb794bbf861807e to Peer{ id: 5, name: peer0.org1.vancir.com, channelName: mychannel, url: grpc://localhost:7051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
        at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4138)
        at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:856)
        at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1779)
        at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1616)
        at org.hyperledger.fabric.sdk.Channel.lambda$null$12(Channel.java:5263)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        ... 3 more
2018-12-14 21:40:30 WARN  Channel:869 - getConfigBlock for channel mychannel failed with peer peer0.org1.vancir.com.  Status FAILURE, details: Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: 3eb2848343a9f86e6d1e3de97748885759b2ecc954607c6b6eb794bbf861807e to Peer{ id: 5, name: peer0.org1.vancir.com, channelName: mychannel, url: grpc://localhost:7051} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}
2018-12-14 21:40:30 ERROR Channel:4138 - Channel Channel{id: 3, name: mychannel} Sending proposal with transaction: 3eb2848343a9f86e6d1e3de97748885759b2ecc954607c6b6eb794bbf861807e to Peer{ id: 6, name: peer1.org1.vancir.com, channelName: mychannel, url: grpc://localhost:7056} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
        at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4138)
        at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:856)
        at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1779)
        at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1616)
        at org.hyperledger.fabric.sdk.Channel.lambda$null$12(Channel.java:5263)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [Org2MSP]
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
```

**Comment by Vancir** [comment]
原因有两个. 
1. 在docker-compose.yml里未将org2的peer0和peer1的环境变量 `CORE_PEER_LOCALMSPID`错误地设置为了`Org1MSP`, 应为`Org2MSP`
2. 在`CreateChannel.java`里, 未能设置好路径变量, 更新为我本地的绝对路径后bug通过. 原本是通过`Config.java`里的字符串变量来获取路径, 也在其中尝试设置了绝对路径, 但依旧报错. 这里还需要再调试解决.
